base:
  project: dvc_pipeline_demo
  random_state: 47
  target_col: quality

data_source:
  local_path : https://raw.githubusercontent.com/TripathiAshutosh/dataset/main/red_wine.csv

split:
  dir : data/splited_train_test
  train_file: train.csv
  test_file : test.csv
  split_ratio: 0.2

process:
  dir : data/processed
  train_file: final_train.csv
  test_file: final_test.csv

train:
  n_set: 10

model_dir : model

